INSERT INTO `carriers` (
      `CarrierCode`,
      `CarrierName`,
      `Location`,
      `AddressLine1`,
      `AddressLine2`,
      `City`,
      `State`,
      `Zip`,
      `Country`,
      `Phone`,
      `Fax`,
      `Email`,
      `Website`,
      `Notes`)
  VALUES ( 
       'ACE',
       'Ace Transportation',
       'Headoffice',
       '123 Main St',
       'St 2',
       'Jersey City',
       'NJ',
       '70123',
       'USA',
       '9739809899',
       '9739999999',
       'sales@acetransport.com',
       'www.acetransport.com',
       'New Carrier - Onboarded 01/01/2021')